/* Sebastian Porteiro para ITER
MIXTER
Strings of languages
*/
MX.Lang = function() {}

var lang = 'en';
var msg = {
    'en' : {
        'reloading': 'Reloading webpage',
        'changing_roles' : 'Changing roles between nodes. Please don\'t close the window until change is done',
        'emergency_on_off': 'enable/disable emergency substitution',
        'suicide': 'suicide',
        'cs_on_off': 'enable/disable CS script',
        'switch_roles': 'switch roles',
        'pipeline': 'Pipeline',
        'form': 'Form',
        'reloading': 'Reloading',
        'changing_roles' : 'Changing roles between nodes. Please do not close the window',
        'emergency_on_off': 'activate/deactivate emergency stream',
        'suicide': 'suicide',
        'cs_on_off': 'activate/deactivate CS',
        'switch_roles': 'switch roles',
        'parrilla': 'Schedule tool.',
        'copia_legal': 'Legal Copy',
        'player': 'Player',
        'control_manual': 'Live assist',
        'novnc': 'noVNC',
        'brave': 'Brave',
        'emergency_4': 'In case of Main or Backup failure, the other node will substitute stream',
        'emergency_0': 'In case of Main or Backup failure, there will be no substitute stream',
        'emergency_1': 'In case of Backup failure, Main will substitute stream',
        'emergency_2': 'In case of Main failure, Backup will substitute stream',
        '2030' : 'Hover the buttons to see info',
        'enable_both':'Activate emergency stream in both nodes',
        'disable_both':'Deactivate emergency stream in both nodes',
        'none_1_src': 'None',
        'shm_1_src': 'SHM memory',
        'udp_1_src': 'UDP',
        'tcp_1_src': 'TCP',
        'rtp_1_src': 'RTP',
        'videotest_1_src': 'Videotestsrc',
        'file_1_src': 'File',
        'ximage_1_src': 'Screen recording',
        'v4l2_1_src': 'Camera',
        'video_1_src': 'Video 1 source',
        'audio_1_src': 'Audio 1 source',
        'color_format_1_src': 'Color format',
        'tcp_ip_1_src': 'TCP IP source 1',
        'tcp_port_1_src': 'TCP port source 1',
        'udp_ip_1_src': 'UDP IP source 1',
        'udp_port_1_src': 'UDP port source 1',
        'tcp_ip_2_src': 'TCP IP source 2',
        'tcp_port_2_src': 'TCP port source 2',
        'udp_ip_2_src': 'UDP IP source 2',
        'udp_port_2_src': 'UDP port source 2',
        'file_path_1_src': 'File path 1',
        'file_path_2_src': 'File path 2',
        'none_sink': 'None',
        'tcp_ip_sink': 'TCP IP destination',
        'tcp_port_sink': 'TCP port destination',
        'udp_ip_sink': 'UDP IP destination',
        'udp_port_sink': 'UDP port destination',
        'shm_sink': 'SHM memory',
        'video_sink': 'Video destination',
        'audio_sink': 'Audio destination',
        'color_format_sink': 'Color format',
        'file_sink': 'File',
        'tcp_sink': 'TCP',
        'udp_sink': 'UDP',
        'rtmp_sink': 'RTMP',
        'window': 'Window',
        'file_bitrate_sink': 'Bitrate',
        'file_duration_sink': 'Duration',
        'file_path_sink': 'Path',
        'file_tmp_path_sink': 'Temp path',
        'Name' : 'Name',
        'input_1' : 'Main input',
        'input_2' : 'Secondary input',
        'output'  : 'Output',
    },
    'es' : {
        'reloading': 'Recargando pagina',
        'changing_roles' : 'Cambiando roles entre nodos. Por favor no cierre la ventana hasta que el cambio finalice',
        'emergency_on_off': 'activar/desactivar señal de emergencia',
        'suicide': 'suicidar',
        'cs_on_off': 'activar/desactivar script CS',
        'switch_roles': 'intercambiar roles',
        'parrilla': 'Herramienta para programar la emision de los distingos medias dentro de la parrilla televisiva.',
        'copia_legal': 'La copia legal alberga todas las emisiones del canal y permite su visualización y descarga',
        'player': 'Panel de control del player principal dentro del sistema de playout. Desde él se configuran las fuentes de entrada y salida del video, junto con otros parámetros',
        'control_manual': 'Visualización secuencial de los shows agendados con la posibilidad de alterar la programación obtenida desde la parrilla',
        'novnc': 'Acceso al escritorio remoto del playout',
        'brave': 'Mezclador de señales. Permite controlar niveles de audio, rotulación en caliente, etc. ',
        'emergency_4': 'En caso de fallar la emisión de Main o Backup, cualquier nodo activo supliría al caído',
        'emergency_0': 'En caso de fallar la emisión de Main o Backup, ningun otro nodo activo supliría al caído',
        'emergency_1': 'En caso de fallar la emisión de Backup, Main lo suple',
        'emergency_2': 'En caso de fallar la emisión de Main, Backup lo suple',
        '2030' : 'Sitúese sobre los botones para ver una breve descripción de cada una de las aplicaciones listadas',
        'enable_both':'Activar señal de emergencia en ambos nodos ',
        'disable_both':'Desactivar señal de emergencia en ambos nodos',
        'pipeline': 'Tubería',
        'form': 'Formulario',
        'none_1_src': 'Nada',
        'shm_1_src': 'Memoria SHM',
        'udp_1_src': 'UDP',
        'tcp_1_src': 'TCP',
        'rtp_1_src': 'RTP',
        'videotest_1_src': 'Videotestsrc',
        'file_1_src': 'Archivo',
        'ximage_1_src': 'Captura pantalla',
        'v4l2_1_src': 'Camara',
        'video_1_src': 'Orígen de video 1',
        'audio_1_src': 'Orígen de audio 1',
        'color_format_1_src': 'Formato de color',
        'tcp_ip_1_src': 'TCP IP orígen 1',
        'tcp_port_1_src': 'TCP puerto orígen 1',
        'udp_ip_1_src': 'UDP IP orígen 1',
        'udp_port_1_src': 'UDP puerto orígen 1',
        'tcp_ip_2_src': 'TCP IP orígen 2',
        'tcp_port_2_src': 'TCP puerto orígen 2',
        'udp_ip_2_src': 'UDP IP orígen 2',
        'udp_port_2_src': 'UDP puerto orígen 2',
        'file_path_1_src': 'Ruta del archivo 1',
        'file_path_2_src': 'Ruta del archivo 2',
        'none_sink': 'Nada',
        'tcp_ip_sink': 'TCP IP destino',
        'tcp_port_sink': 'TCP puerto destino',
        'udp_ip_sink': 'UDP IP destino',
        'udp_port_sink': 'UDP puerto destino',
        'shm_sink': 'Memoria SHM',
        'video_sink': 'Destino de video',
        'audio_sink': 'Destino de audio',
        'color_format_sink': 'Formato de color',
        'file_sink': 'Archivo',
        'tcp_sink': 'TCP',
        'udp_sink': 'UDP',
        'rtmp_sink': 'RTMP',
        'window': 'Ventana',
        'file_bitrate_sink': 'Bitrate del archivo',
        'file_duration_sink': 'Duración',
        'file_path_sink': 'Ruta',
        'file_tmp_path_sink': 'Ruta temporal',
        'Name' : 'Nombre',
        'input_1' : 'Entrada principal',
        'input_2' : 'Entrada secundaria',
        'output'  : 'Salida',
    },
}
//search for strings and translate them
MX.Lang.translate = function() {
    console.log('Translating...');
    $("[t-data]").each(function(k,v) {
        var translation = msg[lang][v.textContent]
        v.textContent = typeof translation != "undefined" ? translation : v.textContent;
    });
}

